### ISSUE TITLE
Static analyzer for development

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/AngouriMath#283]
Alright I feel like we finally need an analyzer for AngouriMath. It would include

- [x] Get back the vsix for debuggability

### Tasks for the analyzer

- [x] Producing warnings/errors for static non-readonly fields without [ThreadStatic]
- [x] Producing warnings/errors for thread static fields which have the default initialization
- [ ] Producing warnings/errors for private fields of records without `Equals` overriden
- [ ] Producing warnings for records which are neither sealed nor abstract
- [ ] Producing warnings for public static classes that are outside of `MathS`
- [ ] Producing warnings for records which are derived of `Entity` but don't have `ToString` overriden
- [ ] Producing warnings for thrown exceptions which don't have `AngouriMathBaseException` as their parent

**Comment by Happypig375** [comment]
Also: Warn when a public class is not in AngouriMath.Core except for Entity, MathS, and SySyn.

**Comment by Happypig375** [comment]
Should be considered as part of v3 redesign, really
